workflows:
  ios-build:
    name: iOS Build
    environment:
      vars:
        XCODE_WORKSPACE: "Scrap.xcworkspace"
        XCODE_SCHEME: "Scrap"
    scripts:
      # 1. Install JS dependencies
      - name: Install JS dependencies
        script: npm install

      # 2. Generate ios/ folder on Codemagic Mac machine
      - name: Generate ios/ folder with Expo
        script: |
          npx expo prebuild --platform ios --non-interactive

      # 3. Install iOS dependencies
      - name: Install CocoaPods
        script: |
          cd ios
          pod install
          cd ..

      # 4. Build iOS archive
      - name: Build iOS archive
        script: |
          xcodebuild \
            -workspace "$XCODE_WORKSPACE" \
            -scheme "$XCODE_SCHEME" \
            -configuration Release \
            -archivePath $CM_BUILD_DIR/ios_archive.xcarchive \
            archive \
            CODE_SIGN_IDENTITY="Apple Distribution" \
            PROVISIONING_PROFILE_SPECIFIER="match AppStore Scrap"

    artifacts:
      - $CM_BUILD_DIR/ios_archive.xcarchive
