workflows:
  ios-build:
    name: iOS Build
    environment:
      flutter: stable
      xcode: latest
      vars:
        APPLE_ID: "scrapzoneglobal@gmail.com"
        APP_STORE_CONNECT_PASSWORD: "qevo-bkbi-hhmw-fppq"
    scripts:
      - name: Install dependencies
        script: flutter pub get

      - name: Build iOS
        script: flutter build ipa --release --no-codesign
    artifacts:
      - build/ios/ipa/*.ipa
    publishing:
      app_store_connect:
        apple_id: $APPLE_ID
        password: $APP_STORE_CONNECT_PASSWORD
