workflows:
  ios-build:
    name: iOS Build
    environment:
      vars:
        APPLE_ID: "scrapzoneglobal@gmail.com"             # your Apple ID
        APP_STORE_CONNECT_PASSWORD: "qevo-bkbi-hhmw-fppq" # app-specific password
    scripts:
      - echo "Starting iOS build for $APPLE_ID"
      - xcodebuild -workspace ios/Runner.xcworkspace -scheme Runner -sdk iphoneos -configuration Release archive -archivePath $CM_BUILD_DIR/Runner.xcarchive
    publishing:
      app_store_connect:
        apple_id: $APPLE_ID
        password: $APP_STORE_CONNECT_PASSWORD
