workflows:
  ios-build:
    name: iOS Build
    environment:
      vars:
        XCODE_WORKSPACE: "ios-scrap-app.xcworkspace"
        XCODE_SCHEME: "ios-scrap-app"
      node: latest
      xcode: latest
    scripts:
      - name: Install dependencies
        script: |
          npm install
          cd ios
          pod install
          cd ..
      - name: Build ipa
        script: |
          xcode-project build-ipa \
            --workspace "$XCODE_WORKSPACE" \
            --scheme "$XCODE_SCHEME"
    artifacts:
      - build/ios/ipa/*.ipa
    publishing:
      app_store_connect:
        apple_id: scrapzoneglobal@gmail.com
        password: $APP_STORE_CONNECT_PASSWORD
