workflows:
  ios-build:
    name: iOS Build
    environment:
      vars:
        APPLE_ID: scrapzoneglobal@gmail.com
        APP_SPECIFIC_PASSWORD: your-app-password-here
    scripts:
      - name: Install JS dependencies
        script: |
          npm install

      - name: Generate ios/ folder if missing
        script: |
          if [ ! -d "ios" ]; then
            echo "⚡ No ios/ folder found, generating with eject..."
            npx react-native eject
          fi

      - name: Install iOS dependencies
        script: |
          cd ios
          pod install --repo-update
          cd ..

      - name: Build iOS
        script: |
          xcodebuild -workspace ios/Scrap.xcworkspace \
            -scheme Scrap \
            -sdk iphoneos \
            -configuration Release archive \
            -archivePath $CM_BUILD_DIR/Scrap.xcarchive

    publishing:
      app_store_connect:
        apple_id: $APPLE_ID
        password: $APP_SPECIFIC_PASSWORD
