workflows:
  ios-build:
    name: iOS Build
    max_build_duration: 60
    environment:
      vars:
        APPLE_ID: scrapzoneglobal@gmail.com
      xcode: 16.4
      cocoapods: default
      node: 20.11.1
    scripts:
      - name: Install JS dependencies
        script: npm install
      - name: Generate ios folder with Expo
        script: npx expo prebuild --platform ios
      - name: Install CocoaPods
        script: |
          cd ios
          pod install
          cd ..
      - name: Build iOS archive
        script: |
          xcodebuild \
            -workspace ios/Scrap.xcworkspace \
            -scheme Scrap \
            -configuration Release \
            -archivePath $CM_BUILD_DIR/ios_archive.xcarchive \
            archive CODE_SIGN_IDENTITY="Apple Distribution" \
            PROVISIONING_PROFILE_SPECIFIER="match AppStore Scrap"
    artifacts:
      - build/ios/ipa/*.ipa
    publishing:
      app_store_connect:
        apple_id: scrapzoneglobal@gmail.com
        password: $APPLE_ID_APP_PASSWORD
