Configuration file error:
5 validation errors for AppStoreConnect
appStoreConnectPassword
  string does not match regex "^([a-z]{4}-){3}[a-z]{4}$"{3}[a-z]{4}$)
appStoreConnectPassword
  string does not match regex "^Encrypted\(.+\)$"$)
appStoreConnectPassword
  string does not match regex "^\$\{?([^:{}]+).*\}?$".*\}?$)
appStoreConnectPassword
  string does not match regex "^\$\{\{\s*inputs\.[a-zA-Z]\w*\s*\}\}"
appStoreConnectPassword ->
  SecureEnvironmentVariable expected dict not str
