workflows:
  ios-build:
    name: iOS Build
    environment:
      vars:
        APPLE_ID: scrapzoneglobal@gmail.com
        APP_SPECIFIC_PASSWORD: aqce-btsv-rllm-khlk
        CM_CERT_PASSWORD: testpassword
      xcode: latest

    scripts:
      - name: Decode and install certificate
        script: |
          base64 -D -i ci/ios_certificate_p12_base64.txt -o ios_certificate.p12
          security create-keychain -p "" build.keychain
          security import ios_certificate.p12 -P "$CM_CERT_PASSWORD" -A -t cert -f pkcs12
          security list-keychains -d user -s build.keychain
          security default-keychain -d user -s build.keychain
          security unlock-keychain -p "" build.keychain
          security set-keychain-settings build.keychain

      - name: Install provisioning profile
        script: |
          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
          base64 -D -i ci/comscrapglobal_mobileprovision_base64.txt -o ~/Library/MobileDevice/Provisioning\ Profiles/app.mobileprovision

      - name: Install JS dependencies
        script: |
          npm install

      - name: Generate ios/ folder with Expo
        script: |
          if [ ! -d "ios" ]; then
            echo "⚡ No ios/ folder found, generating with expo prebuild..."
            npx expo prebuild
          fi

      - name: Install iOS dependencies
        script: |
          cd ios
          pod install --repo-update
          cd ..

      - name: Build iOS
        script: |
          xcodebuild -workspace ios/Scrap.xcworkspace \
            -scheme Scrap \
            -sdk iphoneos \
            -configuration Release archive \
            -archivePath $CM_BUILD_DIR/Scrap.xcarchive

    publishing:
      app_store_connect:
        apple_id: $APPLE_ID
        password: $APP_SPECIFIC_PASSWORD
