workflows:
  ios-workflow:
    name: Build iOS IPA for Scrap
    environment:
      vars:
        XCODE_WORKSPACE: "ios/Scrap.xcworkspace"
        XCODE_SCHEME: "Scrap"
        BUNDLE_ID: "com.scrap.global"
        APPLE_TEAM_ID: YOUR_TEAM_ID_HERE   # Replace with your Apple Team ID
      ios_signing:
        distribution_type: app_store
        bundle_identifier: "com.scrap.global"
      groups:
        - ios_credentials
    scripts:
      - name: Install dependencies
        script: |
          npm install
      - name: Prebuild Expo project
        script: |
          npx expo prebuild --platform ios --non-interactive
      - name: Install CocoaPods
        script: |
          cd ios
          pod install
          cd ..
      - name: Build iOS
        script: |
          xcodebuild \
            -workspace "$XCODE_WORKSPACE" \
            -scheme "$XCODE_SCHEME" \
            -configuration Release \
            -sdk iphoneos \
            -archivePath $CM_BUILD_DIR/ios_archive.xcarchive archive \
            DEVELOPMENT_TEAM=$APPLE_TEAM_ID \
            PRODUCT_BUNDLE_IDENTIFIER=$BUNDLE_ID

          xcodebuild \
            -exportArchive \
            -archivePath $CM_BUILD_DIR/ios_archive.xcarchive \
            -exportOptionsPlist ios/exportOptions.plist \
            -exportPath $CM_BUILD_DIR/ipa
    artifacts:
      - $CM_BUILD_DIR/ipa/*.ipa
    publishing:
      app_store_connect:
        apple_id: $APPLE_ID
        password: $APP_SPECIFIC_PASSWORD
        submit_to_testflight: true
