workflows:
  ios-build:
    name: iOS Build
    environment:
      vars:
        XCODE_WORKSPACE: "Scrap.xcworkspace"
        XCODE_SCHEME: "Scrap"
        PROVISIONING_PROFILE_SPECIFIER: "match AppStore Scrap"
      node: 18
      xcode: 16.4
      cocoapods: default
    cache:
      cache_paths:
        - $HOME/Library/Caches/CocoaPods
        - node_modules
    scripts:
      - name: Install JS dependencies
        script: npm install

      - name: Generate iOS project
        script: |
          npx expo prebuild --platform ios --non-interactive --clean

      - name: Install CocoaPods
        script: |
          cd ios
          pod install
          cd ..

      - name: Build iOS archive
        script: |
          xcodebuild \
            -workspace "$XCODE_WORKSPACE" \
            -scheme "$XCODE_SCHEME" \
            -configuration Release \
            -archivePath $CM_BUILD_DIR/ios_archive.xcarchive \
            archive \
            CODE_SIGN_IDENTITY="Apple Distribution" \
            PROVISIONING_PROFILE_SPECIFIER="$PROVISIONING_PROFILE_SPECIFIER"
    artifacts:
      - ios_archive.xcarchive
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/Products/Release-iphoneos/*.ipa
    publishing:
      email:
        recipients:
          - scrapzoneglobal@gmail.com
